name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  change-detection:
    name: 🔍 Change
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-change-detection.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    permissions:
      contents: read

  cpp-tests-ubuntu:
    name: 🇨 Test 🐧
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
        compiler: [gcc]
        preset: [release]
        run-on-draft: [false]
        include:
          - runs-on: ubuntu-24.04
            compiler: gcc
            preset: debug
            run-on-draft: true
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-ubuntu.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      preset-name: ${{ matrix.preset }}
      run-on-draft: ${{ matrix.run-on-draft }}
    permissions:
      contents: read

  cpp-tests-macos:
    name: 🇨 Test 🍎
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-26]
        compiler: [clang]
        preset: [release]
        run-on-draft: [false]
        include:
          - runs-on: macos-26
            compiler: clang
            preset: debug
            run-on-draft: true
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-macos.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      preset-name: ${{ matrix.preset }}
      run-on-draft: ${{ matrix.run-on-draft }}
    permissions:
      contents: read

  cpp-tests-windows:
    name: 🇨 Test 🏁
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2025, windows-11-arm]
        compiler: [msvc]
        preset: [release-windows]
        run-on-draft: [false]
        include:
          - runs-on: windows-2025
            compiler: msvc
            preset: debug-windows
            run-on-draft: true
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-windows.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      preset-name: ${{ matrix.preset }}
      run-on-draft: ${{ matrix.run-on-draft }}
    permissions:
      contents: read

  cpp-coverage:
    name: 🇨 Coverage
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-coverage.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    permissions:
      contents: read
      id-token: write

  cpp-linter:
    name: 🇨 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-linter)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-linter.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      clang-version: 21
      cpp-linter-extra-args: "-std=c++20"
      files-changed-only: true
      install-pkgs: "nanobind==3.0.1"
      setup-python: true
    permissions:
      contents: read
      pull-requests: write

  python-tests:
    name: 🐍 Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm, macos-26, windows-2025]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-tests.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read

  python-coverage:
    name: 🐍 Coverage
    needs: [change-detection, python-tests]
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-coverage.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    permissions:
      contents: read
      id-token: write

  python-linter:
    name: 🐍 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-linter)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-linter.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      check-stubs: true
      enable-ty: true
      enable-mypy: false
    permissions:
      contents: read

  build-sdist:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-sdist.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    permissions:
      contents: read

  build-wheel:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-26,
            windows-2025,
            windows-11-arm,
          ]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-wheel-cibuildwheel.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read

  # this job does nothing and is only used for branch protection
  required-checks-pass:
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - cpp-tests-ubuntu
      - cpp-tests-macos
      - cpp-tests-windows
      - cpp-coverage
      - cpp-linter
      - python-tests
      - python-coverage
      - python-linter
      - build-sdist
      - build-wheel
    runs-on: ubuntu-slim
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          allowed-skips: >-
            ${{
              !fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && 'cpp-tests-ubuntu,cpp-tests-macos,cpp-tests-windows,cpp-coverage,' || ''
            }}
            ${{
              !fromJSON(needs.change-detection.outputs.run-cpp-linter)
              && 'cpp-linter,' || ''
            }}
            ${{
              !fromJSON(needs.change-detection.outputs.run-python-tests)
              && 'python-tests,python-coverage,' || ''
            }}
            ${{
              !fromJSON(needs.change-detection.outputs.run-python-linter)
              && 'python-linter,' || ''
            }}
            ${{
              !fromJSON(needs.change-detection.outputs.run-cd)
              && 'build-sdist,build-wheel' || ''
            }}
          jobs: ${{ toJSON(needs) }}
